"""Interactive first-run setup. Writes .env, seeds SQLite, enrols the ladder.

Runs non-interactively too (--non-interactive) so it can be re-run safely from
a script; anything already set in .env is kept.
"""
from __future__ import annotations

import argparse
import os
import stat
import sys
from datetime import date

import config
import db

BRIDGE_PW_HELP = """
  Proton Mail Bridge password — this is NOT your Proton account password.

  Proton has no public SMTP/IMAP. Mail goes through Proton Mail Bridge, a desktop
  app that decrypts locally and serves ordinary mail servers on this Mac:

      SMTP  127.0.0.1:1025      IMAP  127.0.0.1:1143     (both STARTTLS)

  To get the password:

    1. Open the Proton Mail Bridge app (install from proton.me/mail/bridge if
       you haven't — and sign in with your Proton account there).
    2. Select your account, then open Mailbox details / Configuration.
    3. Bridge shows a generated username and password for this Mac. Copy the
       PASSWORD it displays.

  Your normal Proton password will NOT work here — it authenticates Bridge to
  Proton, not us to Bridge. If sending fails with an auth error, this is almost
  always the reason.

  Bridge must be RUNNING for anything to send or receive. Turn on
  Settings -> "Start on login" or the scheduled jobs die at every reboot.
"""

FIELDS = [
    ("FROM_ADDR", "Partnerships FROM address (e.g. partnerships@temptationtoken.io)", "", False),
    ("FROM_NAME", "Display name on the From header", "Jim Goetz", False),
    ("PROTON_SMTP_USER", "Proton sending address (the Bridge account, usually same as above)", "", False),
    ("PROTON_BRIDGE_PW", "Proton Bridge password (generated BY Bridge, not your Proton password)", "", True),
    ("SMTP_HOST", "Bridge SMTP host", "127.0.0.1", False),
    ("SMTP_PORT", "Bridge SMTP port", "1025", False),
    ("IMAP_HOST", "Bridge IMAP host", "127.0.0.1", False),
    ("IMAP_PORT", "Bridge IMAP port", "1143", False),
    ("CALENDLY", "Calendly URL", "https://calendly.com/REPLACE-ME", False),
    ("LOOM", "Loom video URL (placeholder is fine for now)", "https://www.loom.com/share/REPLACE-ME", False),
    ("MAIL_ADDR", "Physical mailing address for the CAN-SPAM footer", "", False),
    ("HUNTER_API_KEY", "Hunter.io API key (optional — press Enter to skip)", "", False),
]


def read_existing() -> dict:
    out = {}
    p = config.ROOT / ".env"
    if p.exists():
        for line in p.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                out[k.strip()] = v.strip()
    return out


def write_env(vals: dict) -> None:
    p = config.ROOT / ".env"
    lines = [
        "# tts-outreach configuration. Contains a mail credential — keep it out of git.",
        "# DRY_RUN=true means nothing is ever actually delivered.",
        "",
        f"DRY_RUN={vals.get('DRY_RUN', 'true')}",
        "",
    ]
    for k, *_ in FIELDS:
        if vals.get(k):
            lines.append(f"{k}={vals[k]}")
    lines += [
        "",
        "# Volume caps (per day).",
        f"CAP_WEEK_ONE={vals.get('CAP_WEEK_ONE', '15')}",
        f"CAP_AFTER={vals.get('CAP_AFTER', '25')}",
        "",
        "# Acknowledge copy claims that don't match the deployed contract.",
        "# See claims_guard.py. Live sending is blocked until each id here or the copy is fixed.",
        f"CLAIMS_ACK={vals.get('CLAIMS_ACK', '')}",
        "",
    ]
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(p, stat.S_IRUSR | stat.S_IWUSR)  # 0600 — it holds a password
    print(f"\n  wrote {p} (mode 0600)")


def prompt(vals: dict) -> dict:
    print("\n" + "=" * 74)
    print("  tts-outreach — first-run setup")
    print("=" * 74)
    for key, label, default, secret in FIELDS:
        current = vals.get(key, "") or default
        if key == "PROTON_BRIDGE_PW":
            print(BRIDGE_PW_HELP)
        # The sending address defaults to FROM_ADDR — on Proton they are normally the
        # same, and retyping it is a chance to typo it.
        if key == "PROTON_SMTP_USER" and not current:
            current = vals.get("FROM_ADDR", "")
        shown = ("*" * 8 if current else "") if secret else current
        suffix = f" [{shown}]" if shown else ""
        try:
            got = input(f"  {label}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n  aborted.")
            raise SystemExit(1)
        if key == "PROTON_BRIDGE_PW":
            got = got.replace(" ", "")
        vals[key] = got or current
    vals.setdefault("DRY_RUN", "true")
    return vals


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--non-interactive", action="store_true")
    ap.add_argument("--no-harvest", action="store_true")
    args = ap.parse_args()

    vals = read_existing()
    if not args.non_interactive:
        vals = prompt(vals)
    write_env(vals)

    # Test Bridge immediately. Finding out at 09:07 tomorrow that Bridge was closed is a
    # wasted day of outreach; finding out here costs one line.
    print("\n  Checking Proton Bridge…")
    import importlib
    importlib.reload(config)          # pick up the .env we just wrote
    import bridge
    importlib.reload(bridge)
    ok, lines = bridge.check()
    for ln in lines:
        print(f"    {ln}")
    if ok:
        print("    Bridge is up.")
    else:
        print(f"\n{bridge.RED}    {bridge.BRIDGE_DOWN_MESSAGE}{bridge.OFF}")
        print(f"{bridge.RED}    Setup is saved — open Bridge and run `make status` to confirm.")
        print(f"    Also turn on Bridge -> Settings -> Start on login, or the scheduled")
        print(f"    jobs will stop working after every reboot.{bridge.OFF}")

    print("\n  Seeding database…")
    db.init()
    n = db.import_csv()
    print(f"  {n} agencies loaded into {config.DB_PATH.name}")

    print("\n  Enrolling contactable agencies into the sequence…")
    enrolled = 0
    for row in db.all_agencies():
        if row["status"] in config.CONTACTABLE:
            if db.enroll(row["id"], date.today()):
                enrolled += 1
    print(f"  {enrolled} agencies enrolled (D0/D1/D4 email · D3 DM · D7 FedEx · D12 nurture)")

    if not args.no_harvest:
        print("\n  Now run:  .venv/bin/python harvest.py")
    print("  Then:     .venv/bin/python sender.py          (dry run)")
    print("            .venv/bin/python daily_brief.py --for tomorrow --open\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
