wallet = open('src/config/wallet.js', 'w')
wallet.write("import { createConfig, http } from 'wagmi'\n")
wallet.write("import { base } from 'wagmi/chains'\n")
wallet.write("import { createAppKit } from '@reown/appkit/react'\n")
wallet.write("import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'\n")
wallet.write("import { QueryClient } from '@tanstack/react-query'\n\n")
wallet.write("export const projectId = 'fe98d44a78efa54c5bf113f649176020'\n")
wallet.write("export const queryClient = new QueryClient()\n\n")
wallet.write("const metadata = {\n")
wallet.write("  name: 'Temptation Token',\n")
wallet.write("  description: 'Vote. Win. Earn $TTS on Base.',\n")
wallet.write("  url: 'https://temptationtoken.io',\n")
wallet.write("  icons: ['https://temptationtoken.io/wp-content/uploads/2024/06/Copy-of-Temptation-Token-Coin-1024x1024.webp']\n")
wallet.write("}\n\n")
wallet.write("const networks = [base]\n\n")
wallet.write("export const wagmiAdapter = new WagmiAdapter({\n")
wallet.write("  networks,\n")
wallet.write("  projectId,\n")
wallet.write("  ssr: false\n")
wallet.write("})\n\n")
wallet.write("export const wagmiConfig = wagmiAdapter.wagmiConfig\n\n")
wallet.write("createAppKit({\n")
wallet.write("  adapters: [wagmiAdapter],\n")
wallet.write("  networks,\n")
wallet.write("  projectId,\n")
wallet.write("  metadata,\n")
wallet.write("  features: { analytics: true, email: false, socials: false },\n")
wallet.write("  themeMode: 'dark',\n")
wallet.write("  themeVariables: {\n")
wallet.write("    '--w3m-accent': '#d4af37',\n")
wallet.write("    '--w3m-background-color': '#0c0c14',\n")
wallet.write("    '--w3m-border-radius-master': '8px'\n")
wallet.write("  }\n")
wallet.write("})\n")
wallet.close()
print('wallet.js written OK')

