"""
Shared "copy button" HTML renderer.

The brief referenced an existing dm_copilot.html pattern to reuse — there is no such file
in this repo or anywhere on this machine, so this is a fresh implementation of the same
idea: a single self-contained page where every block of copy has a one-tap Copy button.

Self-contained on purpose. No CDN, no fonts, no network — these pages get opened from a
phone, emailed to an agency, and dropped in a shared drive. Anything external would break
in at least one of those.
"""

from __future__ import annotations

import html
import json

BRAND = {
    "bg": "#0c0c14",
    "card": "#14141f",
    "gold": "#d4af37",
    "gold_light": "#f0d060",
    "text": "#f5f5f5",
    "muted": "#9a9aa8",
    "line": "rgba(212,175,55,.22)",
    "warn": "#ffb020",
}


def _block(item: dict, idx: int) -> str:
    label = html.escape(item.get("label", f"Option {idx}"))
    text = item.get("text", "")
    meta = html.escape(item.get("meta", ""))
    payload = json.dumps(text)  # safe JS string literal, survives quotes/newlines/emoji
    return f"""
  <div class="blk">
    <div class="blk-head">
      <span class="blk-label">{label}</span>
      {f'<span class="blk-meta">{meta}</span>' if meta else ''}
      <button class="copy" data-text='{html.escape(payload, quote=True)}'>Copy</button>
    </div>
    <pre class="blk-body">{html.escape(text)}</pre>
  </div>"""


def render_page(title: str, subtitle: str, compliance_line: str,
                sections: list[dict]) -> str:
    """
    sections: [{ "heading": str, "note": str|None, "items": [{label, text, meta}] }]
    """
    body = []
    for sec in sections:
        body.append(f'<h2>{html.escape(sec["heading"])}</h2>')
        if sec.get("note"):
            body.append(f'<p class="note">{html.escape(sec["note"])}</p>')
        for i, item in enumerate(sec.get("items", []), 1):
            body.append(_block(item, i))

    return f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; background:{BRAND['bg']}; color:{BRAND['text']}; line-height:1.6;
          font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; }}
  .wrap {{ max-width:720px; margin:0 auto; padding:26px 16px 70px; }}
  h1 {{ font-size:1.55rem; color:{BRAND['gold']}; margin:0 0 4px; letter-spacing:-.01em; }}
  .sub {{ color:{BRAND['muted']}; font-size:.88rem; margin:0 0 18px; }}
  h2 {{ font-size:.72rem; text-transform:uppercase; letter-spacing:.1em;
        color:{BRAND['gold']}; margin:30px 0 6px; }}
  .note {{ color:{BRAND['muted']}; font-size:.8rem; margin:0 0 12px; }}
  .compliance {{ border:1px solid {BRAND['warn']}; background:rgba(255,176,32,.09);
                 color:{BRAND['warn']}; border-radius:9px; padding:12px 14px;
                 font-size:.82rem; font-weight:600; margin-bottom:20px; }}
  .blk {{ background:{BRAND['card']}; border:1px solid {BRAND['line']}; border-radius:10px;
          padding:12px 14px; margin-bottom:11px; }}
  .blk-head {{ display:flex; align-items:center; gap:10px; margin-bottom:8px; }}
  .blk-label {{ font-size:.68rem; text-transform:uppercase; letter-spacing:.08em;
                color:{BRAND['muted']}; font-weight:700; }}
  .blk-meta {{ font-size:.68rem; color:{BRAND['muted']}; }}
  .copy {{ margin-left:auto; background:linear-gradient(135deg,{BRAND['gold']},{BRAND['gold_light']});
           color:{BRAND['bg']}; border:0; border-radius:6px; padding:7px 15px;
           font-size:.76rem; font-weight:800; cursor:pointer; flex-shrink:0; }}
  .copy.done {{ background:#2ecc71; }}
  .blk-body {{ margin:0; white-space:pre-wrap; word-wrap:break-word; font-size:.92rem;
               font-family:inherit; color:{BRAND['text']}; }}
  footer {{ margin-top:34px; color:{BRAND['muted']}; font-size:.72rem; line-height:1.7;
            border-top:1px solid rgba(255,255,255,.08); padding-top:14px; }}
</style></head>
<body><div class="wrap">
  <h1>{html.escape(title)}</h1>
  <p class="sub">{html.escape(subtitle)}</p>
  <div class="compliance">⚠️ {html.escape(compliance_line)}</div>
  {''.join(body)}
  <footer>
    Post manually — nothing here auto-posts to any platform, by design (platform ToS).<br>
    Generated by the Temptation Token promo toolkit. Operated by Blockchain Entertainment LLC.
  </footer>
</div>
<script>
document.querySelectorAll('.copy').forEach(function (b) {{
  b.addEventListener('click', async function () {{
    var text = JSON.parse(b.getAttribute('data-text'));
    try {{
      await navigator.clipboard.writeText(text);
    }} catch (e) {{
      // Clipboard API needs a secure context; opening the file over file:// on some
      // browsers is not one. Fall back so the button still works everywhere.
      var ta = document.createElement('textarea');
      ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0';
      document.body.appendChild(ta); ta.select();
      try {{ document.execCommand('copy'); }} finally {{ document.body.removeChild(ta); }}
    }}
    var old = b.textContent;
    b.textContent = 'Copied ✓'; b.classList.add('done');
    setTimeout(function () {{ b.textContent = old; b.classList.remove('done'); }}, 1400);
  }});
}});
</script>
</body></html>"""
